### ISSUE TITLE
Best way to contribute new features I am developing into your code base… if it makes sense at all.

### ISSUE THREAD

**Issue by tmenguy** [cgtobi/netatmo_custom#26]
Hi @cgtobi,

I’m working on an extension to your netatmo integration to :
-expose energy (and not only power) measures (as using a Riemann integral homeassitant is really not accurate vs what is reported by the legrand/netatmo app and websites)
-select the “homes” to be tracked (I have personnaly 2 physical houses , so two homes under the same netatmo/legrand account .. and I don’t want to have the entities of the second one in the homeassitant instance of the first one, but we also have the case where one house has multiple gateways, and in this case you do want to have all homes exposed.

I started coding a bit on my side, forking pyatmo to fix an issue in the energy collection APIs, and some misc issues in the presented devices. I have created also a hacs component of my own for the netatmo part …. And then seen that you do have a netatmo_custom repositories for betas.

So what would be your prefered way?
-I fork your netatmo_custom repo
-I only tweak your build.sh of this repo to point to my own repos
-You don’t care (and it is perfectly fine) of those changes and I keep syncing my own component with your official code from homeassistant core and we don’t put back those features into the main one

Thanks for your work!
BR
Thomas

**Comment by cgtobi** [comment]
Hi Thomas,

you are more than welcome to open a PR against this repo (or pyatmo and HA for that matter) with your changes. I welcome any contributor to pyatmo and the HA integration itself. Also, in case you use Discord, feel free to PM me. I am happy to provide assistance.

Best regards
Tobi

**Comment by tmenguy** [comment]
Hi,

Great! The pyatmo I modify is the one from @jabesq-org, I'll send a pull request when ready there... even if I'll do like you did and just plain copy the pyatmo code right into the custom component for ease of ... well everything :). Yes I'll probably need a bit of guidance at some point especially for the config flow to incorporate the home selection at the right place and point in time...but well before bothering you I'll try to play around.

BR
Thomas
