### ISSUE TITLE
Camera stream failing on doorbell

### ISSUE THREAD

**Issue by confucius78** [cgtobi/netatmo_custom#4]
HA version: 2022.02.9

Issue:
Opening camera stream of the doorbell fails (get error message on-screen). Subsequently, the state of the camera entity becomes "Unavailable". When the instance is initialised, the camera entity shows as "Idle" (which I think is normal behavior), and the actual still preview does seem correct.

Log (redacted ip to xxx.xxx.xxx.xxx):
`2022-03-04 11:39:16 WARNING (stream_worker) [libav.http] HTTP error 404 Not Found
2022-03-04 11:39:16 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.netatmo_netatmo_doorbell_g7c7520] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) http://xxx.xxx.xxx.xxx/2289badb6716942407f35251287f2254/live/files/high/index.m3u8
2022-03-04 11:39:18 ERROR (MainThread) [homeassistant.components.analytics] Error sending analytics to https://analytics-api.home-assistant.io/v1: ClientConnectorError(ConnectionKey(host='analytics-api.home-assistant.io', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-8920893537776734647), ConnectionRefusedError(111, "Connect call failed ('::', 443, 0, 0)"))
2022-03-04 11:40:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved`

**Comment by confucius78** [comment]
Ok, so I have tested per the current release on 6-Mar, findings:

Test steps:
- uninstall integration
- restart HA
- install integration (using configuration.yaml)
- check status of doorbell entity (in dev tools)

  result:
   entity state: idle
   entity attributes (some states were redacted by me):
`access_token: ***REDACTED***
model_name: Smart Video Doorbell
brand: Netatmo
frontend_stream_type: hls
attribution: Data provided by Netatmo
id: 70:ee:50:7c:75:20
monitoring: null
sd_status: 4
alim_status: 2
is_local: true
vpn_url: >-
  https://prodvpn-eu-11.netatmo.net/restricted/10.255.2.226/***REDACTED***,,
local_url: null
light_state: null
entity_picture: >-
  /api/camera_proxy/camera.netatmo_netatmo_doorbell_g7c7520?token=***REDACTED***
friendly_name: Netatmo Netatmo-Doorbell-g7c7520
supported_features: 2`

- check entity in lovelace (visually using picture entity card, without clicking)

  result:
   state: idle
   picture card shows still of the camera image (refreshing every .... seconds)

- Open camera stream (clicking the picture entity card)

  result:
   state: Unavailable
   entity state card stays blank and does not show the camera stream
   entity attributes change to:
    `entity_picture: >-
  /api/camera_proxy/camera.netatmo_netatmo_doorbell_g7c7520?token=04a6bb3bf4927e065a783c1879be8c5192a0e0c7d841a799271df96d9941247b
friendly_name: Netatmo Netatmo-Doorbell-g7c7520
supported_features: 2`
   the picture entity card does continue displaying the stills

Log messages:
No log messages until the last testing step, at which point it seems to spit out the following error every ... seconds:
`Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) https://prodvpn-eu-11.netatmo.net/restricted/10.255.2.226/2289badb6716942407f35251287f2254/MTY0NjU3ODgwMDqEHFbvbbL-pSA7eGoeZoJsMfY2hg,,/live/files/high/index.m3u8`

**Comment by confucius78** [comment]
So as discussed on discord: I did some additional testing after discovering the doorbell stream went unavailable altogether:

1. restart HA -> no success, when checking a picture element in lovelace, blank grey screen and status 'Unavailable'

2. uninstall, restart, re-install, restart: again no image, but with the difference the entity has state 'Idle', which changes to 'Unavailable' after a few minutes

Logs:

> Logger: homeassistant.components.stream.stream.camera.netatmo_netatmo_doorbell_g7c7520
> Source: components/stream/__init__.py:340
> Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
> First occurred: 8:48:59 PM (4 occurrences)
> Last logged: 8:50:30 PM
> 
>     Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) https://prodvpn-eu-9.netatmo.net/restricted/10.255.56.98/2289badb6716942407f35251287f2254/***REDACTED***,,/live/files/high/index.m3u8
>     Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) https://prodvpn-eu-9.netatmo.net/restricted/10.255.56.98/2289badb6716942407f35251287f2254/***REDACTED***,,/live/files/high/index.m3u8

It seems exactly like the previous behavior **after clicking**, as the attributes are also changing to different values.
To be clear: I didn't click on the card to open the stream

**Comment by confucius78** [comment]
Idea...I just noticed the stream on the actual Netatmo app is black. Could it be that by handling the camera as an actual camera, all but one instance are blocked access?

That could explain why you were getting a working image, but it was failing for me...

This was not the case when I started testing this btw, so the last code update initiated this behavior

**Comment by cgtobi** [comment]
Currently the video stream is not publicly available. Therefore we'll stick with the snapshots for now.
