### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by gabry1609** [cgtobi/netatmo_custom#9]
Hello :)

Today, after upgrading the component, I've noticed this error:

Logger: custom_components.netatmo
Source: custom_components/netatmo/__init__.py:199
Integration: Netatmo
First occurred: 06:47:52 (1 occurrences)
Last logged: 06:47:52

Error during webhook registration - 400 - Bad request - Allowed ports for webhooks are 80, 88, 443 and 9443. (21) when accessing 'https://api.netatmo.com/api/addwebhook'

At the moment I'm running the netatmo custom component without having any devices being recognized (because they're still a work in progress).
Thanks in advance!

**Comment by cgtobi** [comment]
As the error message explains you have to expose your system via one of those mentioned ports. I strongly recommend using 443 or using Nabu Casa.
